type: release
name: stream
version: 0.1
description: Demo stream processing
ion: 0.0.1
apps:
  - name: stream_producer
    description: A process which perodically emits a message on a particular stream (routing key)
    version: 0.1
    processapp: [stream_producer, examples.stream.stream_producer, StreamProducer]
    config:
      stream_producer:
        interval: 4000
        routing_key: glider_data

  - name: stream_consumer
    description: A stream process which processes messages from a queue
    version: 0.1
    processapp: [stream_consumer, examples.stream.stream_consumer, StreamConsumer]
    config:
      process:
        listen_name: consumer_input_queue



  - name: stream_binder
    description: Takes the place of calling pubsub to subscribe and activate subscription
    version: 0.1
    processapp: [stream_binder, examples.stream.stream_binder, StreamBinder]
    config:
      args:
        queue_name: consumer_input_queue
        binding: glider_data
