# This file configures the OOI asset import for development

load_sequence:

  - name: load_OOIR2_scenario
    docstring:
    config:
      op: load
      scenario: OOIR2
      path: master

  - name: load_instrument_scenarios
    docstring:
    config:
      op: load
      scenario: CTDBP,PREST
      ooiexclude: DataProduct,DataProductLink,Deployment,Workflow,WorkflowDefinition


  - name: load_ooi_assets
    docstring:
    config:
      op: load
      loadooi: True
      assets: res/preload/r2_ioc/ooi_assets
      bulk: True
      debug: True
      ooiuntil: "9/1/2013"
      #ooiexclude: DataProduct,DataProductLink,Deployment,Workflow,WorkflowDefinition
