# This file configures the OOI asset import for development

load_sequence:

  - name: load_OOIR2_scenario
    docstring:
    config:
      op: load
      scenario: OOIR2
      path: master

  - name: load_parameter_scenarios
    docstring:
    config:
      op: load
      scenario: BETA
      path: master
      categories: ParameterFunctions,ParameterDefs,ParameterDictionary,StreamDefinition
      clearcols: owner_id,org_ids

  - name: load_OOIR2_agents
    docstring:
    config:
      op: load
      scenario: OOIR2_I
      path: master

  - name: load_ooi_assets
    docstring:
    config:
      op: load
      loadooi: True
      path: master
      assets: res/preload/r2_ioc/ooi_assets
      bulk: True
      debug: True
      ooiuntil: "9/1/2013"
      ooiparams: True
      #excludecategories: DataProduct,DataProductLink,Deployment,Workflow,WorkflowDefinition
      revert: True

  - name: load_OOIR2_demo
    docstring:
    config:
      op: load
      scenario: OOIR2_DEMO
      path: master
      debug: True
      revert: True
      idmap: True
