# This file configures the OOI alpha instance configuration

load_sequence:
  - name: load_ooi_assets
    docstring: Apply OOI preload idempotently to generate all missing OOI resources
    config:
      op: load
      loadooi: True
      assets: res/preload/r2_ioc/ooi_assets
      ooiuntil: "12/31/2013"
      ooiparams: True
