# This file configures the official OOI instrument import

load_sequence:

  - name: load_OOIR2_ctdbp
    docstring:
    config:
      op: load
      path: master
      scenario: CTDBP,PRESF,PREST,TMPSF,VEL3D_B
      idmap: True
      excludecategories: InstrumentAgent,InstrumentModel
      revert: True
