# This file configures the OOI alpha instance configuration

load_sequence:

  # Copied from ooi_load_config.yml
  - name: load_OOIR2_ui
    docstring: Loads the UI definition
    config:
      op: loadui
      ui_path: 'http://userexperience.oceanobservatories.org/database-exports/Candidates'
      attachments: res/preload/r2_ioc/attachments

  - name: load_OOIR2_scenario
    docstring: Loads the basic OOI resources, such as Orgs, Users etc
    config:
      op: load
      scenario: OOIR2

  - name: load_parameter_scenarios
    docstring: Loads basic shared parameter and stream resources
    config:
      op: load
      scenario: BETA
      categories: ParameterFunctions,ParameterDefs,ParameterDictionary,StreamDefinition
      clearcols: owner_id,org_ids
      assets: res/preload/r2_ioc/ooi_assets
      parseooi: True

  - name: load_OOIR2_agents
    docstring: Loads OOI agent definitions, needed for OOI asset preload
    config:
      op: load
      scenario: OOIR2_I

  - name: load_ooi_assets
    docstring: Main OOI preload fed by SAF and OOI preload spreadsheet shources
    config:
      op: load
      loadooi: True
      assets: res/preload/r2_ioc/ooi_assets
      ooiuntil: "9/1/2013"
      ooiparams: True


  # THIS IS THE ACTUAL ALPHA SPECIALIZATION
  - name: load_OOIR2_demo
    docstring: Some simulators with data products
    config:
      op: load
      scenario: OOIR2_DEMO
      idmap: True

  - name: load_OOIR2_alpha
    docstring: Specialize for alpha (port agent addresses in InstrumentAgentInstance)
    config:
      op: load
      scenario: OOIR2_ALPHA


  # Copied from ooi_instruments.yml
  - name: load_OOIR2_instruments
    docstring: Load physical instrument sites, devices and agent instance definitions
    config:
      op: load
      scenario: VEL3D_B
      idmap: True
      excludecategories: InstrumentAgent,InstrumentModel

  - name: load_OOIR2_OPTAA_CTDPF
    docstring: Load physical instrument sites, devices and agent instance definitions
    config:
      op: load
      scenario: OPTAA,CTDPF
      idmap: True
      excludecategories: InstrumentModel
      revert: True
