# This file configures the official OOI asset import for the "summer 2013" deployments

load_sequence:

  - name: load_OOIR2_scenario
    docstring:
    config:
      op: load
      scenario: OOIR2
      path: master

  - name: load_ooi_assets
    docstring:
    config:
      op: load
      loadooi: True
      assets: res/preload/r2_ioc/ooi_assets
      bulk: False
      debug: False
      ooiuntil: "9/1/2013"
      excludecategories: DataProduct,DataProductLink,Deployment,Workflow,WorkflowDefinition
