# This file configures the official OOI asset import for the "summer 2013" deployments

load_sequence:

  - name: load_ooi
    docstring:
    config:
      op: load
      scenario: OOI
      loadooi: True
      assets: res/preload/r2_ioc/ooi_assets
      bulk: False
      debug: False
      ooiuntil: "9/1/2013"
      ooiexclude: DataProduct,DataProductLink,Deployment,Workflow,WorkflowDefinition

#  - name: step2:
#    config:
#      ooiexclude:
