# This file configures the OOI alpha instance configuration

load_sequence:

  # Copied from ooi_load_config.yml
  - name: load_OOIR2_ui
    docstring:
    config:
      op: loadui
      ui_path: 'https://userexperience.oceanobservatories.org/database-exports/Stable'
      attachments: res/preload/r2_ioc/attachments

  - name: load_OOIR2_scenario
    docstring:
    config:
      op: load
      scenario: OOIR2

  - name: load_parameter_scenarios
    docstring:
    config:
      op: load
      scenario: BETA
      categories: ParameterFunctions,ParameterDefs,ParameterDictionary,StreamDefinition
      clearcols: owner_id,org_ids

  - name: load_OOIR2_agents
    docstring:
    config:
      op: load
      scenario: OOIR2_I

  - name: load_ooi_assets
    docstring:
    config:
      op: load
      loadooi: True
      assets: res/preload/r2_ioc/ooi_assets
      ooiuntil: "9/1/2013"


  # THIS IS THE ACTUAL ALPHA SPECIALIZATION
  - name: load_OOIR2_demo
    docstring:
    config:
      op: load
      scenario: OOIR2_X

  - name: load_OOIR2_alpha
    docstring:
    config:
      op: load
      path: master
      scenario: OOIR2_ALPHA
      revert: True


  # Copied from ooi_instruments.yml
  - name: load_OOIR2_ctdbp
    docstring:
    config:
      op: load
      path: master
      scenario: CTDBP,PRESF,PREST,TMPSF,VEL3D_B
      idmap: True
      excludecategories: InstrumentAgent,InstrumentModel
      revert: True
