# associations.yml

# This is the authoritative definition of all permissible association types in the system

AssociationTypes:
  hasAttachment:
    domain: [InstrumentDevice]
    range: [Attachment]
#SA 
  hasChildDataProducer:
    domain: [DataProducer]
    range: [DataProducer]
  hasInputDataProducer:
    domain: [DataProducer]
    range: [DataProducer]
  hasDataset:
    domain: [DataProducer, DataProduct]
    range: [Dataset]
  hasDataProducer:
    domain: [DataProduct, InstrumentDevice]
    range: [DataProducer]
  hasInputProduct:
    domain: [DataProcess]
    range: [DataProduct]
  hasOutputProduct:
    domain: [DataProcess]
    range: [DataProduct]
  hasTransform:
    domain: [DataProcess]
    range: [Transform]
  hasSite:
    domain: [MarineFacility, Site]
    range: [Site]
  hasInstrument:
    domain: [PlatformDevice]
    range: [InstrumentDevice]
  hasModel:
    domain: [PlatformDevice, InstrumentDevice, Sensor, InstrumentAgent, PlatformAgent]
    range: [PlatformModel, InstrumentModel, SensorModel]
  hasPlatform:
    domain: [MarineFacility, Site, PlatformLogical]
    range: [PlatformDevice, PlatformLogical]
  hasAssignment:
    domain: [PlatformDevice, InstrumentDevice]
    range: [PlatformLogical, InstrumentLogical]
  hasAgentInstance:
    domain: [PlatformDevice, InstrumentDevice]
    range: [PlatformAgentInstance,InstrumentAgentInstance]
  hasInstance:
    domain: [PlatformAgent, InstrumentAgent]
    range: [PlatformAgentInstance, InstrumentAgentInstance]
  hasSensor:
    domain: [InstrumentDevice]
    range: [Sensor]
# DM
  hasCatalog:
    domain: [View]
    range: [Catalog]
  hasDatastore:
    domain: [View, Index]
    range: [Datastore]
  hasIndex:
    domain: [Catalog]
    range: [Index]
  hasArchive:
    domain: [Datastore]
    range: [PersistentArchive]
  hasTransform:
    domain: [DataProcess]
    range: [Transform]
  hasStream:
    domain: [DataProcess, DataProducer, Dataset, ExchangePoint, Subscription]
    range: [Stream]
  hasOutStream:
    domain: [Transform]
    range: [Stream]
  hasTopology:
    domain: [Stream, Subscription]
    range: [TopicTopology]
  hasProcessDefinition:
    domain: [Transform]
    range: [ProcessDefinition]
  hasSubscription:
    domain: [Transform, ExchangePoint]
    range: [Subscription]
  hasTopicTopology:
    domain: [ExchangePoint]
    range: [TopicTopology]
# COI
  hasBroker:
    domain: [ExchangeSpace]
    range: [ExchangeBroker]
  hasExchangeSpace:
    domain: [Org]
    range: [ExchangeSpace]
  hasExchangePoint:
    domain: [ExchangeSpace]
    range: [ExchangePoint]
  hasExchangeName:
    domain: [ExchangeSpace]
    range: [ExchangeName]
  hasCredentials:
    domain: [UserIdentity]
    range: [UserCredentials]
  hasInfo:
    domain: [UserIdentity]
    range: [UserInfo]
  hasRole:
    domain: [Conversation,UserIdentity]
    range: [ConversationRole,UserRole]
  hasType:
    domain: [Conversation]
    range: [ServiceDefinition]
  hasAgent:
    domain: [TaskableReource]
    range: [Agent]
  hasPolicy:
    domain: [Resource]
    range: [Policy]
  hasOwner:
    domain: [Resource]
    range: [UserIdentity]
  hasLifecycle:
    domain: [Resource]
    range: [ResourceLifecycle]
# Examples
  hasAccount:
    domain: [BankCustomer]
    range: [BankAccount]
