# associations.yml

# This is the authoritative definition of all permissible association predicates in the system

# WARNING: !!! Make sure the same predicate does NOT occur twice in the list below !!!

PredicateTypes:
#SA
  hasAssignment: # DEPRECATE (use hasDevice)
    domain: [PlatformDevice, InstrumentDevice]
    range: [InstrumentSite, PlatformSite]
  hasDataset:
    domain: [DataProducer, DataProduct]
    range: [DataSet]
  hasDataProducer:
    domain: [DataProcess, Device, ExternalDataset, DataProduct]
    range: [DataProducer]
  hasDataProduct:
    domain: [Site]
    range: [DataProduct]
  hasDevice:
    domain: [Site, Device]
    range: [Device]
  hasDeployment:
    domain: [Device, InstrumentSite, PlatformSite]
    range: [Deployment, InstrumentSite, PlatformSite]
  hasInputDataProducer:
    domain: [DataProducer]
    range: [DataProducer]
  hasInputProduct:
    domain: [DataProcess]
    range: [DataProduct]
  hasInstance: # DEPRECATE (use hasDefinition)
    domain: [AgentDefinition, DataProcessDefinition]
    range: [AgentInstance, DataProcess]
  hasInstrument:  # DEPRECATE
    domain: [PlatformDevice, PlatformSite]
    range: [InstrumentDevice, InstrumentSite]
  hasModel:
    domain: [Device, Site, AgentDefinition, DataSource, ExternalDataset]
    range: [DeviceModel]
  hasObservatory: # DEPRECATE
    domain: [Org]
    range: [Observatory]
  hasOutputProduct:
    domain: [DataProcess, Device, ExternalDataset]
    range: [DataProduct]
  hasParent:
    domain: [DataProducer]
    range: [DataProducer]
  hasPrimaryDeployment: # DEPRECATE (use Deployment resource)
    domain: [PlatformDevice, InstrumentDevice]
    range: [InstrumentSite, PlatformSite]
  hasSensor: # DEPRECATE (use hasDevice)
    domain: [InstrumentDevice]
    range: [SensorDevice]
  hasSite:
    domain: [Site]
    range: [Site]
# DM
  hasCatalog:
    domain: [View]
    range: [Catalog]
  hasDataStore:
    domain: [PersistenceSystem]
    range: [DataStore]
  hasIndex:
    domain: [Catalog, DataStore]
    range: [Index]
  hasIngestionConfiguration:
    domain: [DataSet, DatasetIngestionConfiguration]
    range: [IngestionConfiguration]
  hasInputStreamDefinition:
    domain: [DataProcessDefinition]
    range: [StreamDefinition]
  hasNotification:
    domain: [ActorIdentity]
    range: [NotificationRequest]
  hasOutStream:
    domain: [Transform]
    range: [Stream]
  hasStream:
    domain: [Replay, DataProcess, DataProduct, DataSet, ExchangePoint, Subscription]
    range: [Stream]
  hasStreamDefinition:
    domain: [Stream, InstrumentModel, DataProcessDefinition]
    range: [StreamDefinition]
  hasSubscription:
    domain: [Transform, ExchangePoint]
    range: [Subscription]
  hasTopology:
    domain: [ExchangePoint, Stream, Subscription]
    range: [TopicTopology]
  hasTransform:
    domain: [DataProcess, IngestionConfiguration]
    range: [Transform]
# COI
  affiliatedWith:
    domain: [Org]
    range: [Org]
  committedTo:
    domain: [Commitment]
    range: [ActorIdentity]
  hasAgent: # DEPRECATE (don't use)
    domain: [InstrumentSite, PlatformSite]
    range: [InstrumentAgent, PlatformAgent]
  hasAgentDefinition:
    domain: [DeviceModel, Site]
    range: [AgentDefinition]
  hasAgentInstance:
    domain: [TaskableResource, Device, DataSource, ExternalDataset]
    range: [AgentInstance]
  hasAttachment:
    domain: [Resource]
    range: [Attachment]
  hasCommitment:
    domain: [ActorIdentity, Resource]
    range: [Commitment]
  hasCredentials:
    domain: [ActorIdentity]
    range: [UserCredentials]
  hasDefinition:
    domain: [TaskableResource]
    range: [ExecutableResource]
  hasExchangeBroker:
    domain: [ExchangeSpace]
    range: [ExchangeBroker]
  hasExchangeName:
    domain: [ExchangeSpace]
    range: [ExchangeName]
  hasExchangePoint:
    domain: [ExchangeSpace]
    range: [ExchangePoint]
  hasExchangeSpace:
    domain: [Org]
    range: [ExchangeSpace]
  hasInfo:
    domain: [ActorIdentity]
    range: [UserInfo]
  hasLifecycle:
    domain: [ResourceType]
    range: [ResourceLifecycle]
  hasMembership:
    domain: [Org]
    range: [ActorIdentity]
  hasOwner:
    domain: [Resource]
    range: [ActorIdentity]
  hasPolicy:
    domain: [Resource]
    range: [Policy]
  hasRequest:
    domain: [Org, ActorIdentity]
    range: [UserRequest,UserRequest]
  hasResource:
    domain: [Org, Collection]
    range: [Resource]
  hasRole:
    domain: [Conversation, ActorIdentity, Org]
    range: [ConversationRole, UserRole]
  hasConversationType:
    domain: [Conversation, ServiceDefinition]
    range: [ConversationType]
# CEI
  hasProcessDefinition:
    domain: [Resource]
    range: [ProcessDefinition, DataProcessDefinition]
  supportsExecutionEngine:
    domain: [ProcessDefinition]
    range: [ExecutionEngineDefinition]
# EOI
  hasProvider:
    domain: [DataSource]
    range: [ExternalDataProvider]
  hasSource:
    domain: [ExternalDataset]
    range: [DataSource]
# UX
  hasUIGroup:
    domain: [UIResource]
    range: [UIResource]
  hasUIScreenLabel:
    domain: [UIResource]
    range: [UIResource]
  hasUIBlockAttribute:
    domain: [UIResource]
    range: [UIResource]
  hasUIAttribute:
    domain: [UIResource]
    range: [UIResource]
  hasUIBlockRepresentation:
    domain: [UIResource]
    range: [UIResource]
  hasUIRepresentation:
    domain: [UIResource]
    range: [UIResource]
  hasUIGroupBlock:
    domain: [UIResource]
    range: [UIResource]
  hasUIBlock:
    domain: [UIResource]
    range: [UIResource]
  hasUIViewGroup:
    domain: [UIResource]
    range: [UIResource]
  hasUISupertype:
    domain: [UIResource]
    range: [UIResource]
  hasUIResource:
    domain: [UIResource]
    range: [UIResource]

# Examples
  hasAccount:
    domain: [BankCustomer]
    range: [BankAccount]
  
