handlers:
  pycc_file:
    class: logging.FileHandler
    filename: logs/pycc_logfile.txt

loggers:
  pyon:
    handlers: [pycc_file]
    level: INFO
  ion:
    handlers: [pycc_file]
    level: INFO
  prototype:
    handlers: [pycc_file]
    level: INFO
