# Place parameter dictionary definitions here

# An example param dict definition for temperature
temp_param_dict:
  lat: !Lat
  lon: !Lon
  time: !Time
  depth: !Depth
  temperature: !Temperature

---

# An example param dict definition for conductivity
cond_param_dict:
  lat: !Lat
  lon: !Lon
  time: !Time
  depth: !Depth
  conductivity: !Conductivity

---

# An example param dict definition for salinity
sal_param_dict:
  lat: !Lat
  lon: !Lon
  time: !Time
  depth: !Depth
  salinity: !Salinity


