# Place parameter dictionary definitions here

# An example param dict definition for temperature
temp_param_dict:
  lat: ""
  lon: ""
  time: ""
  depth: ""
  temperature: ""

---

# An example param dict definition for conductivity
cond_param_dict:
  lat: ""
  lon: ""
  time: ""
  depth: ""
  conductivity: ""

---

# An example param dict definition for salinity
sal_param_dict:
  lat: ""
  lon: ""
  time: ""
  depth: ""
  salinity: ""

