# Place parameter context definitions here

Lat:
  param_type: QuantityType(value_encoding=np.float32)
  ref_frame: AxisTypeEnum.LAT
  uom: "degree_north"
  fill_value: 0e0
  docstring: References the latitude

Lon:
  param_type: QuantityType(value_encoding=np.float32)
  ref_frame: AxisTypeEnum.LON
  uom: "degree_east"
  fill_value: 0e0
  docstring: References the longitude

Time:
  param_type: QuantityType(value_encoding=np.int64)
  ref_frame: AxisTypeEnum.TIME
  uom: "seconds since 1970-01-01"
  fill_value: 0e0
  docstring: References the time

Depth:
  param_type: QuantityType(value_encoding=np.float32)
  ref_frame: AxisTypeEnum.HEIGHT
  uom: "meters"
  fill_value: 0e0
  docstring: References the depth

Temperature:
  param_type: QuantityType(value_encoding=np.float32)
  uom: "degree_Celsius"
  fill_value: 0e0
  docstring: References the temperature

Conductivity:
  param_type: QuantityType(value_encoding=np.float32)
  uom: "siemens_per_meter"
  fill_value: 0e0
  docstring: References the conductivity

Salinity:
  param_type: QuantityType(value_encoding=np.float32)
  uom: "PSU"
  fill_value: 0e0
  docstring: References the salinity

Pressure:
  param_type: QuantityType(value_encoding=np.float32)
  uom: "Pascal"
  fill_value: 0e0
  docstring: References the pressure

Raw:
  param_type: QuantityType(value_encoding=np.float32)
  uom: "unknown"
  fill_value: 0e0
  docstring: References raw data


