# Place parameter dictionary definitions here

# Example parameter dictionary definition
sample_param_dict: ['lat', 'lon', 'time', 'depth', 'salinity', 'temp', 'pressure', 'conductivity']
ctd_parsed_param_dict: ['lat', 'lon', 'time', 'depth', 'salinity', 'temp', 'pressure', 'conductivity']
ctd_raw_param_dict: ['time']
data_particle_parsed_param_dict: ['port_timestamp', 'driver_timestamp', 'internal_timestamp', 'depth', 'conductivity', 'temp', ] #'preferred_timestamp', 'quality_flag', ]
data_particle_raw_param_dict: ['port_timestamp', 'driver_timestamp', 'internal_timestamp', ] #'preferred_timestamp', 'quality_flag', 'raw']
satlantic_par_parsed_param_dict: ['port_timestamp', 'driver_timestamp', 'internal_timestamp', 'serial_num', 'timer', 'counts', 'checksum', ] #'preferred_timestamp', 'quality_flag']