binary:
  comment: null
  _derived_from_name: binary
  long_name: null
  standard_name: null
  code_reports: null
  param_type:
    fill_value: 0
    description: ''
    extension: {}
    constraint: null
    cm_type: !!python/tuple [coverage_model.parameter_types, QuantityType]
    _template_attrs: {fill_value: -9999, quality: null, uom: unspecified, nilValues: null,
      constraint: null}
    _value_module: coverage_model.parameter_values
    label: ''
    uom: unknown
    mutable: false
    _identifier: null
    _id: null
    quality: null
    _value_encoding: '|u1'
    nilValues: null
    _value_class: NumericValue
  variable_reports: null
  references_list: null
  label: ''
  mutable: false
  variability: 3
  reference_frame: null
  ooi_short_name: null
  description: ''
  ion_name: null
  _identifier: null
  cm_type: !!python/tuple [coverage_model.parameter, ParameterContext]
  name: binary
  extension: {}
  index_key: null
  cdm_data_type: null
  attributes: null
  _id: null
temp:
  comment: null
  _derived_from_name: temp
  long_name: null
  standard_name: null
  code_reports: null
  param_type:
    fill_value: 0.0
    description: ''
    extension: {}
    constraint: null
    cm_type: !!python/tuple [coverage_model.parameter_types, QuantityType]
    _template_attrs: {fill_value: -9999, quality: null, uom: unspecified, nilValues: null,
      constraint: null}
    _value_module: coverage_model.parameter_values
    label: ''
    uom: degree_Celsius
    mutable: false
    _identifier: null
    _id: null
    quality: null
    _value_encoding: <f4
    nilValues: null
    _value_class: NumericValue
  variable_reports: null
  references_list: null
  label: ''
  mutable: false
  variability: 3
  reference_frame: null
  ooi_short_name: null
  description: ''
  ion_name: null
  _identifier: null
  cm_type: !!python/tuple [coverage_model.parameter, ParameterContext]
  name: temp
  extension: {}
  index_key: null
  cdm_data_type: null
  attributes: null
  _id: null
lon:
  comment: null
  _derived_from_name: lon
  long_name: null
  standard_name: null
  code_reports: null
  param_type:
    fill_value: 0.0
    description: ''
    extension: {}
    constraint: null
    cm_type: !!python/tuple [coverage_model.parameter_types, QuantityType]
    _template_attrs: {fill_value: -9999, quality: null, uom: unspecified, nilValues: null,
      constraint: null}
    _value_module: coverage_model.parameter_values
    label: ''
    uom: degree_east
    mutable: false
    _identifier: null
    _id: null
    quality: null
    _value_encoding: <f4
    nilValues: null
    _value_class: NumericValue
  variable_reports: null
  references_list: null
  label: ''
  mutable: false
  variability: 3
  reference_frame: 6
  ooi_short_name: null
  description: ''
  ion_name: null
  _identifier: null
  cm_type: !!python/tuple [coverage_model.parameter, ParameterContext]
  name: lon
  extension: {}
  index_key: null
  cdm_data_type: null
  attributes: null
  _id: null
salinity:
  comment: null
  _derived_from_name: salinity
  long_name: null
  standard_name: null
  code_reports: null
  param_type:
    fill_value: 0
    description: ''
    extension: {}
    constraint: null
    cm_type: !!python/tuple [coverage_model.parameter_types, QuantityType]
    _template_attrs: {fill_value: -9999, quality: null, uom: unspecified, nilValues: null,
      constraint: null}
    _value_module: coverage_model.parameter_values
    label: ''
    uom: PSU
    mutable: false
    _identifier: null
    _id: null
    quality: null
    _value_encoding: <f4
    nilValues: null
    _value_class: NumericValue
  variable_reports: null
  references_list: null
  label: ''
  mutable: false
  variability: 3
  reference_frame: null
  ooi_short_name: null
  description: ''
  ion_name: null
  _identifier: null
  cm_type: !!python/tuple [coverage_model.parameter, ParameterContext]
  name: salinity
  extension: {}
  index_key: null
  cdm_data_type: null
  attributes: null
  _id: null
pressure:
  comment: null
  _derived_from_name: pressure
  long_name: null
  standard_name: null
  code_reports: null
  param_type:
    fill_value: 0
    description: ''
    extension: {}
    constraint: null
    cm_type: !!python/tuple [coverage_model.parameter_types, QuantityType]
    _template_attrs: {fill_value: -9999, quality: null, uom: unspecified, nilValues: null,
      constraint: null}
    _value_module: coverage_model.parameter_values
    label: ''
    uom: Pascal
    mutable: false
    _identifier: null
    _id: null
    quality: null
    _value_encoding: <f4
    nilValues: null
    _value_class: NumericValue
  variable_reports: null
  references_list: null
  label: ''
  mutable: false
  variability: 3
  reference_frame: null
  ooi_short_name: null
  description: ''
  ion_name: null
  _identifier: null
  cm_type: !!python/tuple [coverage_model.parameter, ParameterContext]
  name: pressure
  extension: {}
  index_key: null
  cdm_data_type: null
  attributes: null
  _id: null
depth:
  comment: null
  _derived_from_name: depth
  long_name: null
  standard_name: null
  code_reports: null
  param_type:
    fill_value: 0.0
    description: ''
    extension: {}
    constraint: null
    cm_type: !!python/tuple [coverage_model.parameter_types, QuantityType]
    _template_attrs: {fill_value: -9999, quality: null, uom: unspecified, nilValues: null,
      constraint: null}
    _value_module: coverage_model.parameter_values
    label: ''
    uom: meters
    mutable: false
    _identifier: null
    _id: null
    quality: null
    _value_encoding: <f4
    nilValues: null
    _value_class: NumericValue
  variable_reports: null
  references_list: null
  label: ''
  mutable: false
  variability: 3
  reference_frame: 4
  ooi_short_name: null
  description: ''
  ion_name: null
  _identifier: null
  cm_type: !!python/tuple [coverage_model.parameter, ParameterContext]
  name: depth
  extension: {}
  index_key: null
  cdm_data_type: null
  attributes: null
  _id: null
time:
  comment: null
  _derived_from_name: time
  long_name: null
  standard_name: null
  code_reports: null
  param_type:
    fill_value: 0
    description: ''
    extension: {}
    constraint: null
    cm_type: !!python/tuple [coverage_model.parameter_types, QuantityType]
    _template_attrs: {fill_value: -9999, quality: null, uom: unspecified, nilValues: null,
      constraint: null}
    _value_module: coverage_model.parameter_values
    label: ''
    uom: seconds since 1970-01-01
    mutable: false
    _identifier: null
    _id: null
    quality: null
    _value_encoding: <i8
    nilValues: null
    _value_class: NumericValue
  variable_reports: null
  references_list: null
  label: ''
  mutable: false
  variability: 3
  reference_frame: 12
  ooi_short_name: null
  description: ''
  ion_name: null
  _identifier: null
  cm_type: !!python/tuple [coverage_model.parameter, ParameterContext]
  name: time
  extension: {}
  index_key: null
  cdm_data_type: null
  attributes: null
  _id: null
lat:
  comment: null
  _derived_from_name: lat
  long_name: null
  standard_name: null
  code_reports: null
  param_type:
    fill_value: 0.0
    description: ''
    extension: {}
    constraint: null
    cm_type: !!python/tuple [coverage_model.parameter_types, QuantityType]
    _template_attrs: {fill_value: -9999, quality: null, uom: unspecified, nilValues: null,
      constraint: null}
    _value_module: coverage_model.parameter_values
    label: ''
    uom: degree_north
    mutable: false
    _identifier: null
    _id: null
    quality: null
    _value_encoding: <f4
    nilValues: null
    _value_class: NumericValue
  variable_reports: null
  references_list: null
  label: ''
  mutable: false
  variability: 3
  reference_frame: 5
  ooi_short_name: null
  description: ''
  ion_name: null
  _identifier: null
  cm_type: !!python/tuple [coverage_model.parameter, ParameterContext]
  name: lat
  extension: {}
  index_key: null
  cdm_data_type: null
  attributes: null
  _id: null
conductivity:
  comment: null
  _derived_from_name: conductivity
  long_name: null
  standard_name: null
  code_reports: null
  param_type:
    fill_value: 0.0
    description: ''
    extension: {}
    constraint: null
    cm_type: !!python/tuple [coverage_model.parameter_types, QuantityType]
    _template_attrs: {fill_value: -9999, quality: null, uom: unspecified, nilValues: null,
      constraint: null}
    _value_module: coverage_model.parameter_values
    label: ''
    uom: unknown
    mutable: false
    _identifier: null
    _id: null
    quality: null
    _value_encoding: <f4
    nilValues: null
    _value_class: NumericValue
  variable_reports: null
  references_list: null
  label: ''
  mutable: false
  variability: 3
  reference_frame: null
  ooi_short_name: null
  description: ''
  ion_name: null
  _identifier: null
  cm_type: !!python/tuple [coverage_model.parameter, ParameterContext]
  name: conductivity
  extension: {}
  index_key: null
  cdm_data_type: null
  attributes: null
  _id: null
