# Minimal configuration file for bootstrapping the ION container,
# system and services via the directory.
# Note: override with pyon.local.yml
system:
  root_org: ION

# Config values to allow discovery of the directory
container:
  directory:
    server: couchdb

server:
  couchdb:
    # The basic CouchDB connection
    type: couchdb
    host: localhost
    port: 5984
    username:
    password:
