# Minimal configuration file for bootstrapping the ION container,
# system and services via the directory.
system:
  name:
  root_org: ION
  force_clean: False
  # Indicates this container should not bootstrap the directory.
  # Rather, it should get its configuration from the directory.
  auto_bootstrap: False


# Config values to allow discovery of the directory
container:
  directory:
    server: couchdb

server:
  couchdb:
    # The basic CouchDB connection
    type: couchdb
    host: localhost
    port: 5984
    username:
    password:

