# Minimal configuration file for bootstrapping the ION container,
# system and services via the directory.
# Note: override with pyon.local.yml and pycc command line args
system:
  root_org: ION
  auto_bootstrap: True

server:
  couchdb:
    # The basic CouchDB connection
    type: couchdb
    host: localhost
    port: 5984
    username:
    password:

# Config values to allow discovery of the directory
container:
  profile: development
