type: release
name: cei_deploy
version: 0.1
description: Common Execution Infrastructure Services
ion: 0.0.1
apps:

  # dependencies

  - name: directory
    version: 0.1
    processapp: [directory, ion.services.coi.directory_service, DirectoryService]

  - name: datastore
    description: Data store service
    version: 0.1
    processapp: [datastore, ion.services.coi.datastore_service, DataStoreService]

  - name: resource_registry
    description: Resource registry service
    version: 0.1
    processapp: [resource_registry, ion.services.coi.resource_registry_service, ResourceRegistryService]


  # CEI services - only including ones with an actual implementation at this point

  - name: process_dispatcher
    description: Process dispatcher service (bridge)
    version: 0.1
    processapp: [process_dispatcher, ion.services.cei.process_dispatcher_service, ProcessDispatcherService]
