type: release
name: r2coi
version: 0.1
description: R2 COI services deployment configuration
ion: 2.0
apps:
  ##################################
  # CORE SERVICES
  # Bootstrap processes perform initializations
  ##################################

  - name: event_persister
    processapp: [event_persister, ion.processes.event.event_persister, EventPersister]
    bootlevel: 1

  - name: bootstrapper1
    processapp: [bootstrapper1, ion.processes.bootstrap.bootstrapper, Bootstrapper]
    bootlevel: 2
    config:
      bootstrap_plugins:
        - plugin: [ion.processes.bootstrap.plugins.bootstrap_core, BootstrapCore]

  - name: resource_registry
    processapp: [resource_registry, ion.services.coi.resource_registry_service, ResourceRegistryService]
    bootlevel: 5

  - name: directory
    processapp: [directory, ion.services.coi.directory_service, DirectoryService]
    bootlevel: 8

  - name: identity_management
    processapp: [identity_management, ion.services.coi.identity_management_service, IdentityManagementService]
    bootlevel: 8

  - name: policy_management
    processapp: [policy_management, ion.services.coi.policy_management_service, PolicyManagementService]
    bootlevel: 8

  - name: exchange_management
    processapp: [exchange_management, ion.services.coi.exchange_management_service, ExchangeManagementService]
    bootlevel: 8

  - name: org_management
    processapp: [org_management, ion.services.coi.org_management_service, OrgManagementService]
    bootlevel: 8

  - name: bootstrapper2
    processapp: [bootstrapper2, ion.processes.bootstrap.bootstrapper, Bootstrapper]
    bootlevel: 9
    config:
      bootstrap_plugins:
        - plugin: [ion.processes.bootstrap.plugins.bootstrap_org, BootstrapOrg]

  ##################################
  # HIGHER LEVEL SERVICES
  ##################################

  ##### COI SERVICES
  - name: agent_management
    processapp: [agent_management, ion.services.coi.agent_management_service, AgentManagementService]
    bootlevel: 10

  - name: conversation_management
    processapp: [conversation_management, ion.services.coi.conversation_management_service, ConversationManagementService]
    bootlevel: 10

#  - name: object_management
#    processapp: [object_management, ion.services.coi.object_management_service, ObjectManagementService]
#    bootlevel: 10
#
#  - name: resource_management
#    processapp: [resource_management, ion.services.coi.resource_management_service, ResourceManagementService]
#    bootlevel: 10
#
#  - name: service_management
#    processapp: [service_management, ion.services.coi.service_management_service, ServiceManagementService]
#    bootlevel: 10

  - name: bootstrapper3
    processapp: [bootstrapper3, ion.processes.bootstrap.bootstrapper, Bootstrapper]
    deploy:
      bootlevel: 20
    config:
      bootstrap_plugins:
        - plugin: [ion.processes.bootstrap.plugins.bootstrap_service, BootstrapService]

  #The bootstrap for loading policy should be the final bootstrap process.
  - name: policy_bootstrap
    processapp: [policy_bootstrap, ion.processes.bootstrap.bootstrapper, Bootstrapper]
    bootlevel: 29
    config:
      bootstrap_plugins:
        - plugin: [ion.processes.bootstrap.plugins.bootstrap_policy, BootstrapPolicy]

  # LAST SERVICE GATEWAY SERVICE
  - name: service_gateway
    processapp: [service_gateway, ion.services.coi.service_gateway_service, ServiceGatewayService]
    deploy:
      bootlevel: 30
