type: release
name: r2deploy
version: 0.1
description: Release 2 deployment configuration
ion: 0.0.1
apps:
  - name: bootstrap
    version: 0.1
    processapp: [bootstrap, ion.core.bootstrap_service, BootstrapService]

  - name: datastore
    description: Data store service
    version: 0.1
    processapp: [datastore, ion.services.coi.datastore_service, DataStoreService]
    config:
        datastore:
            persistent: true
            force_clean: true

  - name: directory
    version: 0.1
    processapp: [directory, ion.services.coi.directory_service, DirectoryService]

  - name: resource_registry
    description: Resource registry service
    version: 0.1
    processapp: [resource_registry, ion.services.coi.resource_registry_service, ResourceRegistryService]
    config:
        resource_registry:
            persistent: true
            force_clean: true
