type: release
name: r2deploy
version: 0.1
description: Release 2 deployment configuration
ion: 0.0.1
apps:
  ##################################
  # CORE SERVICES
  # Bootstrapper app performs initializations
  ##################################

  - name: bootstrap
    version: 0.1
    processapp: [bootstrap, ion.core.bootstrap_service, BootstrapService]

  - name: datastore
    description: Data store service
    version: 0.1
    processapp: [datastore, ion.services.coi.datastore_service, DataStoreService]
    config:
        datastore:
            persistent: true
            force_clean: true

  - name: bootstrap
    config:
      level: datastore

  - name: directory
    version: 0.1
    processapp: [directory, ion.services.coi.directory_service, DirectoryService]
    config:
        directory:
            persistent: true
            force_clean: true

  - name: bootstrap
    config:
      level: directory

  - name: resource_registry
    description: Resource registry service
    version: 0.1
    processapp: [resource_registry, ion.services.coi.resource_registry_service, ResourceRegistryService]
    config:
        resource_registry:
            persistent: true
            force_clean: true

  - name: bootstrap
    config:
      level: resource_registry

  - name: identity_management
    version: 0.1
    processapp: [identity_management, ion.services.coi.identity_management_service, IdentityManagementService]

  - name: bootstrap
    config:
      level: identity_management

  - name: org_management
    version: 0.1
    processapp: [org_management, ion.services.coi.org_management_service, OrgManagementService]

  - name: bootstrap
    config:
      level: org_management

  - name: exchange_management
    version: 0.1
    processapp: [exchange_management, ion.services.coi.exchange_management_service, ExchangeManagementService]

  - name: bootstrap
    config:
      level: exchange_management

  ##################################
  # HIGHER LEVEL SERVICES
  ##################################

