type: release
name: r2deploy
version: 0.1
description: Release 2 deployment configuration
ion: 0.0.1
apps:
  ##################################
  # CORE SERVICES
  # Bootstrapper app performs initializations
  ##################################

  - name: bootstrap
    version: 0.1
    processapp: [bootstrap, ion.core.bootstrap_service, BootstrapService]

  - name: datastore
    description: Data store service
    version: 0.1
    processapp: [datastore, ion.services.coi.datastore_service, DataStoreService]

  - name: bootstrap
    config:
      level: datastore

  - name: directory
    version: 0.1
    processapp: [directory, ion.services.coi.directory_service, DirectoryService]

  - name: bootstrap
    config:
      level: directory

  - name: resource_registry
    description: Resource registry service
    version: 0.1
    processapp: [resource_registry, ion.services.coi.resource_registry_service, ResourceRegistryService]

  - name: bootstrap
    config:
      level: resource_registry

  - name: identity_management
    version: 0.1
    processapp: [identity_management, ion.services.coi.identity_management_service, IdentityManagementService]

  - name: bootstrap
    config:
      level: identity_management

  - name: policy_management
    version: 0.1
    processapp: [policy_management, ion.services.coi.policy_management_service, PolicyManagementService]

  - name: org_management
    version: 0.1
    processapp: [org_management, ion.services.coi.org_management_service, OrgManagementService]

  - name: bootstrap
    config:
      level: org_management

  - name: exchange_management
    version: 0.1
    processapp: [exchange_management, ion.services.coi.exchange_management_service, ExchangeManagementService]

  - name: bootstrap
    config:
      level: exchange_management

  ##################################
  # HIGHER LEVEL SERVICES - TODO: CORRECT ORDER NEEDS TO BE FIGURED OUT ONCE IMPLEMENTATION HAS BEEN COMPLETED
  ##################################

  ##### COI SERVICES
  - name: agent_management
    version: 0.1
    processapp: [agent_management, ion.services.coi.agent_management_service, AgentManagementService]

  - name: conversation_management
    version: 0.1
    processapp: [conversation_management, ion.services.coi.conversation_management_service, ConversationManagementService]

  - name: object_management
    version: 0.1
    processapp: [object_management, ion.services.coi.object_management_service, ObjectManagementService]

  - name: resource_management
    version: 0.1
    processapp: [resource_management, ion.services.coi.resource_management_service, ResourceManagementService]

  - name: service_management
    version: 0.1
    processapp: [service_management, ion.services.coi.service_management_service, ServiceManagementService]

  - name: state_repository
    version: 0.1
    processapp: [state_repository, ion.services.coi.state_repository_service, StateRepositoryService]

  - name: service_gateway
    version: 0.1
    processapp: [service_gateway, ion.services.coi.service_gateway_service, ServiceGatewayService]


# SA services


  - name: data_product_management
    version: 0.1
    processapp: [data_product_management, ion.services.sa.product.data_product_management_service, DataProductManagementService]

  - name: instrument_management_service
    version: 0.1
    processapp: [instrument_management_service, ion.services.sa.instrument.instrument_management_service, InstrumentManagementService]

  - name: marine_facility_management
    version: 0.1
    processapp: [marine_facility_management, ion.services.sa.marine_facility.marine_facility_management_service, MarineFacilityManagementService]


