# This file configures the OOI asset import

import_sequence:
  - name: step1
    config:
      op: load
      scenario: OOI
      loadooi: True
      assets: res/preload/r2_ioc/ooi_assets
      bulk: True
      debug: True
      ooiuntil: "8/1/2013"
      ooiexclude: DataProduct,DataProductLink,Deployment,Workflow,WorkflowDefinition

#  - name: step2:
#    config:
#      ooiexclude:
